### PR TITLE
Feature/parservisibilityfix

### PR DESCRIPTION
**Pull request by Christophe668**
I changed the visibility of the 'Parser' interface aswell as the 'GsonParser' you already had in the library.

I also added a test of the 'setParser' inside the sample app with a provided implementation of the gson parser which is parsing DateTime objects. 

The line `Hawk.get("joda")` was returning null before the custom parser was set. It is now parsing the object correctly and does not return null anymore.

### CODE REVIEW

**Comment by orhanobut** [comment]
Great! Just a few notes, 
- Could you use 2 space indentation instead of 4? 
- Also I think we can completely remove app folder since we cover everything on test, I really don't see any value on app anymore.
- Can you squash all your commits into one as well?


Thanks

**Comment by Christophe668** [comment]
You want to delete the app module entirely ? 
Ok, I'll check also how I can squatch commits even if I already pushed them.

**Comment by orhanobut** [comment]
Yes, let's remove completely please, and for squash thing, when you squash your commits, you need to force push unfortunately.

**Comment by Christophe668** [comment]
Done, I think it should be ok, tell me if something went wrong. First time I make a pulll request so I hope it's ok. Thanks !

**Comment by orhanobut** [comment]
That's perfectly fine now :) Thanks for the PR

**Pull request merged**
