### PR TITLE
Update Conceal and Android support library

### PR DESCRIPTION
**Pull request by alphater**
1, updated cryptographic library Conceal v1 to v2 ; [upgrade notes](https://github.com/facebook/conceal#upgrade-notes)
2, update the Android support library to 27.1.0 (due to 27 so the minimum version upgrade to 14);

### CODE REVIEW

**Comment by alphater** [comment]
@orhanobut  Why fails to build when upgrading to 4.1? Has been built locally.

**Comment by orhanobut** [comment]
Awesome! Let me check the issue soon and see why it fails. Btw why don't we just update conceal version through maven? I think that'd be much better option and easier to update.

**Comment by alphater** [comment]
@orhanobut  Yes, it is indeed more convenient to update through experts. I have already realized that this issue has been modified into an expert in the local, but this was not submitted successfully, so no later changes can be made.

**Comment by orhanobut** [comment]
@alphater Do you mean the artifacts are not present in maven central? That'd be weird.

**Comment by orhanobut** [comment]
Going to push a change-set which includes these updates as well. Therefore closing this one. Thanks for the changes and bumping versions 👍

**Pull request closed without merging**
