### PR TITLE
Added setParser() to HawkBuilder

### PR DESCRIPTION
**Pull request by if12b062**
Implementation to use a different parser for de-/serialization which was curiously not possible until now.

### CODE REVIEW

**Comment by orhanobut** [comment]
Thanks! it looks great.

**Comment by Christophe668** [comment]
Hi Orhan is the 1.19 already available? I'd like to try the new setParser() method which is not available yet with the 1.18. 
Thanks !

**Comment by orhanobut** [comment]
@Christophe668 I had really no time to build a new version, I'll move all to jitpack, thus we can have a build in a very short time, today I'll try to move things.

**Comment by Christophe668** [comment]
Great, thank you !

**Comment by orhanobut** [comment]
Pushed the new version, there is a small change with the distribution which will be jitpack from now on in order to have fast new versions.

**Pull request merged**
